FROM golang:1.20 as builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o service ./cmd/service/main.go

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/service .
CMD ["./consumer"]
