version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: deploy/Dockerfile.service
    container_name: service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
      - kafka
    networks:
      - go-payment-network
      
  consumer:
    build:
      context: .
      dockerfile: deploy/Dockerfile.consumer
    container_name: consumer
    restart: always
    depends_on:
      - database
      - kafka
    networks:
      - go-payment-network

  database:
    image: postgres:15
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gopayments_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go-payment-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - go-payment-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - go-payment-network

volumes:
  pgdata:

networks:
  go-payment-network:
    driver: bridge
