server:
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "secret"
  name: "payment_db"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

kafka:
  broker: "localhost:9092"
  topic: "transactions"
  
metrics:
  port: "9090"